<digit> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
<separator> ::= "," "."
<number> ::= <digit> | <digit> <number>
<float> ::= <number> <separator> <number>
<other> ::= "b" <number> "a"
